# Component interaction custom IDs
BIRTHDAY_CONFIG_PREFIX = "birthday_cfg:"
BIRTHDAY_PREFIX = "birthday:"

# Region → list of (IANA timezone, display label)
TIMEZONE_REGIONS: dict[str, list[tuple[str, str]]] = {
    "Americas": [
        ("America/New_York", "Eastern (New York)"),
        ("America/Chicago", "Central (Chicago)"),
        ("America/Denver", "Mountain (Denver)"),
        ("America/Los_Angeles", "Pacific (Los Angeles)"),
        ("America/Anchorage", "Alaska"),
        ("Pacific/Honolulu", "Hawaii"),
        ("America/Phoenix", "Arizona (no DST)"),
        ("America/Toronto", "Toronto"),
        ("America/Vancouver", "Vancouver"),
        ("America/Mexico_City", "Mexico City"),
        ("America/Bogota", "Bogota"),
        ("America/Lima", "Lima"),
        ("America/Santiago", "Santiago"),
        ("America/Sao_Paulo", "São Paulo"),
        ("America/Argentina/Buenos_Aires", "Buenos Aires"),
    ],
    "Europe": [
        ("Europe/London", "London (GMT/BST)"),
        ("Europe/Dublin", "Dublin"),
        ("Europe/Paris", "Paris"),
        ("Europe/Berlin", "Berlin"),
        ("Europe/Amsterdam", "Amsterdam"),
        ("Europe/Madrid", "Madrid"),
        ("Europe/Rome", "Rome"),
        ("Europe/Zurich", "Zurich"),
        ("Europe/Stockholm", "Stockholm"),
        ("Europe/Warsaw", "Warsaw"),
        ("Europe/Helsinki", "Helsinki"),
        ("Europe/Athens", "Athens"),
        ("Europe/Bucharest", "Bucharest"),
        ("Europe/Moscow", "Moscow"),
        ("Europe/Istanbul", "Istanbul"),
    ],
    "Asia & Pacific": [
        ("Asia/Dubai", "Dubai (GST)"),
        ("Asia/Kolkata", "India (IST)"),
        ("Asia/Dhaka", "Dhaka"),
        ("Asia/Bangkok", "Bangkok (ICT)"),
        ("Asia/Singapore", "Singapore"),
        ("Asia/Shanghai", "Shanghai (CST)"),
        ("Asia/Hong_Kong", "Hong Kong"),
        ("Asia/Taipei", "Taipei"),
        ("Asia/Tokyo", "Tokyo (JST)"),
        ("Asia/Seoul", "Seoul (KST)"),
        ("Australia/Perth", "Perth (AWST)"),
        ("Australia/Adelaide", "Adelaide (ACST)"),
        ("Australia/Sydney", "Sydney (AEST)"),
        ("Pacific/Auckland", "Auckland (NZST)"),
        ("Pacific/Fiji", "Fiji"),
    ],
    "Africa & Middle East": [
        ("Africa/Cairo", "Cairo"),
        ("Africa/Lagos", "Lagos (WAT)"),
        ("Africa/Nairobi", "Nairobi (EAT)"),
        ("Africa/Johannesburg", "Johannesburg (SAST)"),
        ("Africa/Casablanca", "Casablanca"),
        ("Asia/Jerusalem", "Jerusalem"),
        ("Asia/Riyadh", "Riyadh"),
        ("Asia/Tehran", "Tehran"),
    ],
}
