apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discord-bot-prod
spec:
  selector:
    matchLabels:
      app: discord-bot-prod
  serviceName: discord-bot-prod
  replicas: 1
  template:
    metadata:
      labels:
        app: discord-bot-prod
    spec:
      # initContainers:
      #   - name: discord-data-permission-fix
      #     image: busybox
      #     command: ["/bin/chown", "-R", "101", "/app/state"]
      #     volumeMounts:
      #       - name: my-do-volume
      #         mountPath: /app/state
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: discord-bot-prod
          image: ghcr.io/dragonpaw/discord-bot/discord-bot:stable
          command:
            - /app/bin/start
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 250m
              memory: 120Mi
          envFrom:
            - secretRef:
                name: discord-bot-prod
          volumeMounts:
            - name: discord-bot-prod-state
              mountPath: /app/state
  volumeClaimTemplates:
    - metadata:
        name: discord-bot-prod-state
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
