apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discord-bot-test
spec:
  selector:
    matchLabels:
      app: discord-bot-test
  serviceName: discord-bot-test
  replicas: 1
  template:
    metadata:
      labels:
        app: discord-bot-test
    spec:
      # initContainers:
      #   - name: discord-data-permission-fix
      #     image: busybox
      #     command: ["/bin/chown", "-R", "101", "/app/state"]
      #     volumeMounts:
      #       - name: my-do-volume
      #         mountPath: /app/state
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
      # Used to pull private packages from github. (If needed. Remove otherwise.)
      # imagePullSecrets:
      #   - name: regcred
      containers:
        - name: discord-bot-test
          image: ghcr.io/dragonpaw/discord-bot/discord-bot:latest
          imagePullPolicy: Always
          command:
            - /app/bin/start
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 250m
              memory: 120Mi
          envFrom:
            - secretRef:
                name: discord-bot-test
          volumeMounts:
            - name: discord-bot-test-state
              mountPath: /app/state
  volumeClaimTemplates:
    - metadata:
        name: discord-bot-test-state
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
