apiVersion: apps/v1
kind: Deployment
metadata:
  name: sites
  namespace: ash
spec:
  selector:
    matchLabels:
      pod: sites
  replicas: 1
  template:
    metadata:
      labels:
        pod: sites
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: sites
          image: ghcr.io/dragonpaw/sites/sites:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 30Mi
