channel = "roles"

# --------------------------------------------------------------------------
#                                   Gender
# --------------------------------------------------------------------------
[[menu]]
name = "Gender"
single = true
options = [
  { role = "Male", description = "Please use 'he/him' when referring to me.", emoji = "male_sign" },
  { role = "Female", description = "Please use 'she/her' when referring to me.", emoji = "female_sign" },
  { role = "Nonbinary", description = "Please use 'they/them' when referring to me.", emoji = "no_entry_sign" },
]

# --------------------------------------------------------------------------
#                                    Trans
# --------------------------------------------------------------------------
[[menu]]
name = "Transitional"
description = "You may use this role, if you wish, to let people know that you are trans. This is a **completely optional thing**. (If you feel that trans people should be required to 'warn' you that they are trans, please leave this server.)"
options = [
  { role = "Trans", description = "I'm trans. Deal with it.", emoji = "+1" },
]

# --------------------------------------------------------------------------
#                              Direct Messaging
# --------------------------------------------------------------------------
[[menu]]
name = "DM Permission"
single = true
options = [
  { role = "DM: Open", description = "Feel free to DM me any time, no need to ask.", emoji = "white_check_mark" },
  { role = "DM: Ask", description = "Please ask publicly first. (If I am Owned, please ask the person who Owns me.)", emoji = "question" },
]
