channel = "roles"

# --------------------------------------------------------------------------
# D/s roles
# --------------------------------------------------------------------------
[[menu]]
description = "Please let us know how you identify, in terms of traditional D/s role."
name = "D/s roles"
single = true
options = [
  { role = "Dominant", description = "I like to make people get me coffee.", emoji = "coffee" },
  { role = "submissive", description = "I like to fetch coffee.", emoji = "YesSir1" },
  { role = "Switch", description = "Sometimes I fetch the coffee, sometimes someone fetches me the coffee.", emoji = "switch" },
]

# --------------------------------------------------------------------------
# Gender
# --------------------------------------------------------------------------
[[menu]]
name = "Gender"
single = true
options = [
  { role = "Male", description = "Please use 'he/him' when referring to me.", emoji = "male_sign" },
  { role = "Female", description = "Please use 'she/her' when referring to me.", emoji = "female_sign" },
  { role = "Nonbinary", description = "Please use 'they/them' when referring to me.", emoji = "no_entry_sign" },
  { role = "It/Its", description = "Please use 'it/its' when referring to me.", emoji = "dolls" },
]

# --------------------------------------------------------------------------
# Trans
# --------------------------------------------------------------------------
[[menu]]
description = "You may use this role, if you wish, to let people know that you are trans. This is a **completely optional thing**. (If you feel that trans people should be required to 'warn' you that they are trans, please leave this server.)"
name = "Trans"
options = [
  { role = "Trans", description = "I'm trans. Deal with it.", emoji = "+1" },
]

# --------------------------------------------------------------------------
# Direct Messaging
# --------------------------------------------------------------------------
[[menu]]
name = "DM Permission"
single = true
options = [
  { role = "DM: Open", description = "Feel free to DM me any time, no need to ask.", emoji = "white_check_mark" },
  { role = "DM: Ask", description = "Please ask publicly first. (If I am Owned, please ask the person who Owns me.)", emoji = "question" },
]

# --------------------------------------------------------------------------
# Misc Kinks
# --------------------------------------------------------------------------
[[menu]]
description = "What kinda stuff are you into, or curious about?"
name = "Misc Kinks"
options = [
  { role = "Bondage", description = "I like to be restrained, or to restrain others.", emoji = "ballgag" },
  { role = "Rigger", description = "I really, **really**, like using rope as a means of bondage on other people.", emoji = "Rope" },
  { role = "rope bottom", description = "I love being tied up with rope as the scene itself, not just to facilitate another scene.", emoji = "firecracker" },
  { role = "Discipline", description = "I love structure and knowing the rules. Clear boundaries let me feel safe to explore.", emoji = "YesMaster" },
  { role = "24/7", description = "Not just a bedroom thing — I live, or want to live, a D/s lifestyle 24/7.", emoji = "clock1" },
  { role = "Sadist", description = "I get hard/wet at hurting people.", emoji = "PinkPaddle" },
  { role = "masochist", description = "I get hard/wet at being hurt.", emoji = "Spank" },
  { role = "Top", description = "I get off on topping people in some form: tying them up, flogging them, etc.", emoji = "arrow_up" },
  { role = "Service Top", description = "I top when asked and tailor the scene to the bottom. I get off on them getting off.", emoji = "arrow_double_up" },
  { role = "bottom", description = "I love to be topped: i.e. flogged, tied up, and generally used.", emoji = "arrow_down" },
  { role = "Pet play", description = "I love to run around with ears and a tail in me.", emoji = "tailswish" },
  { role = "Heal Slut", description = "I love mixing sex and video games — e.g. toys controlled while gaming.", emoji = "joystick" },
]

# --------------------------------------------------------------------------
# Pings
# --------------------------------------------------------------------------
[[menu]]
description = "What kind of things would you like pinged for?"
name = "Pings"
options = [
  { role = "Join VC", description = "Ping me for voice chat!", emoji = "joinvc" },
  { role = "Sluts on Cam", description = "Ping me when people are being sluts on camera!", emoji = "Lunashy" },
  { role = "Warframe", description = "Ping me when it's time to do space ninja shit!", emoji = "LotusSymbol" },
  { role = "Apex Legends", description = "Ping me when you want someone to cause mayhem in Apex with!", emoji = "apex" },
  { role = "Minecraft", description = "Ping me for Minecraft related things!", emoji = "redstone" },
  { role = "Cards Against Humanity", description = "Ping me when we're playing Cards Against Humanity!", emoji = "cah" },
  { role = "SF Local Events", description = "Ping me for events in the San Francisco Bay Area!", emoji = "ashyes" },
  { role = "Littles Support", description = "Ping me to help support any littles that need it.", emoji = "ambulance" },
  { role = "Among Us", description = "Ping me to murder you! (But like in secret)", emoji = "among_us" },
]
