menus: list(include('menu'))
role_channel: str(required=False)
new_member_role: str(required=False)
meta: include('meta', required=False)
---
menu:
  name: str()
  single: bool(required=False)
  description: str(required=False)
  options: list(include('options'))

options:
  emoji: str()
  role: str()
  description: str()

meta:
  last: int()
  url: str()
  size: int()
